package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerHistory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("customerAttribute")
	private java.lang.Boolean customerAttribute;

	public CustomerHistory() {
	}

	public java.lang.Boolean getCustomerAttribute() {
		return this.customerAttribute;
	}

	public void setCustomerAttribute(java.lang.Boolean customerAttribute) {
		this.customerAttribute = customerAttribute;
	}

	public CustomerHistory(java.lang.Boolean customerAttribute) {
		this.customerAttribute = customerAttribute;
	}

}