package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerProfile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CustomerName")
	private java.lang.String customerName;
	@org.kie.api.definition.type.Label("CustomerAccountNum")
	private java.lang.String customerAccountNum;
	@org.kie.api.definition.type.Label("RecentEventsModel")
	private com.TrainingModel recentEventsModel;

	@org.kie.api.definition.type.Label(value = "CustomerEvents")
	private java.util.List<com.Event> customerEvents;

	public CustomerProfile() {
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.String getCustomerAccountNum() {
		return this.customerAccountNum;
	}

	public void setCustomerAccountNum(java.lang.String customerAccountNum) {
		this.customerAccountNum = customerAccountNum;
	}

	public com.TrainingModel getRecentEventsModel() {
		return this.recentEventsModel;
	}

	public void setRecentEventsModel(com.TrainingModel recentEventsModel) {
		this.recentEventsModel = recentEventsModel;
	}

	public java.util.List<com.Event> getCustomerEvents() {
		return this.customerEvents;
	}

	public void setCustomerEvents(java.util.List<com.Event> customerEvents) {
		this.customerEvents = customerEvents;
	}

	public CustomerProfile(java.lang.String customerName,
			java.lang.String customerAccountNum,
			com.TrainingModel recentEventsModel,
			java.util.List<com.Event> customerEvents) {
		this.customerName = customerName;
		this.customerAccountNum = customerAccountNum;
		this.recentEventsModel = recentEventsModel;
		this.customerEvents = customerEvents;
	}

}