package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eventAnalysis implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("eventEffectiveness")
	private java.lang.String eventEffectiveness;
	@org.kie.api.definition.type.Label("eventResponsePayload")
	private java.lang.String eventResponsePayload;

	public eventAnalysis() {
	}

	public java.lang.String getEventEffectiveness() {
		return this.eventEffectiveness;
	}

	public void setEventEffectiveness(java.lang.String eventEffectiveness) {
		this.eventEffectiveness = eventEffectiveness;
	}

	public java.lang.String getEventResponsePayload() {
		return this.eventResponsePayload;
	}

	public void setEventResponsePayload(java.lang.String eventResponsePayload) {
		this.eventResponsePayload = eventResponsePayload;
	}

	public eventAnalysis(java.lang.String eventEffectiveness,
			java.lang.String eventResponsePayload) {
		this.eventEffectiveness = eventEffectiveness;
		this.eventResponsePayload = eventResponsePayload;
	}

	@Override
	public String toString() {
		return "eventAnalysis{" +
				"eventEffectiveness='" + eventEffectiveness + '\'' +
				", eventResponsePayload='" + eventResponsePayload + '\'' +
				'}';
	}
}